# Generated by Django 3.1.2 on 2020-10-29 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20201029_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='photo_11',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='photo_12',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='photo_13',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='photo_14',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='photo_15',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='photo_16',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='photo_17',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='photo_18',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='photo_19',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='photo_20',
        ),
    ]
