# Generated by Django 3.1.2 on 2020-10-29 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='kWh',
            field=models.IntegerField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='sale_type',
            field=models.CharField(choices=[('For Sale', 'For Sale'), ('For Rent', 'For Rent'), ('Owned', 'Owned'), ('Sub-Rent', 'Sub Rent')], default='For Sale', max_length=50),
        ),
    ]
