# Generated by Django 3.1.2 on 2020-10-29 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20201029_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='kWh',
            field=models.IntegerField(default='0'),
        ),
    ]
